"""Demag (magnetostatic) field calculator built on neuralmag.

The demag field is the long-range, geometry-coupled term in the LLG effective
field: solving it cheaply and exactly here lets the neural surrogate spend its
capacity on the short-range interactions (exchange, anisotropy) instead of
re-learning a global convolution.

neuralmag computes the field as an FFT convolution of the magnetization with a
precomputed demag tensor `N` that depends only on the mesh geometry (cell count
+ cell size). We build that tensor once via neuralmag's `State`/`DemagField`
machinery at construction time, store it as a (non-trainable) buffer, and apply
neuralmag's `h_cell` convolution on every call. The module is therefore a pure,
jit/vmap-friendly Equinox module with no learnable parameters.

**Discretization.** A neuralmag solver runs on a *2D* mesh of `n = (nx, ny)` cells
and stores `m` on the **nodes**, i.e. `(nx+1, ny+1)` values. The convolution,
however, is cell-based,
so a nodal call has to follow neuralmag's own node kernel (see
`neuralmag.field_terms.demag_field.DemagField.register`):

    m_node --to_cell--> m_cell --h_cell--> h_cell --to_node_w--> h_node

Both projections are mass-lumped and generated by neuralmag for this mesh; we
resolve them once at construction. Skipping them (treating the nodal grid as a
cell grid) is not a harmless approximation: it gets the field wrong by >100%.

Data written by a *cell-centred* solver (magnum.np, i.e. the `the_well` datasets
under `datasets/`) has no such projection: `m` lives on the `n = (nx, ny)` cells
themselves, and `nodal=False` applies `h_cell` to it directly.
"""

import logging as _logging
from collections.abc import Callable
from functools import lru_cache
from pathlib import Path

import equinox as eqx
import jax.numpy as jnp
import neuralmag as nm
from jaxtyping import Array
from neuralmag.backends.jax.demag_field import h_cell

# neuralmag logs its setup at INFO on every State build (one per model
# construction); keep the training/eval output readable.
nm.set_log_level(_logging.WARNING)

# The mesh geometry is fixed across runs, so the demag tensor is built once and
# reused (keyed on n/dx/pbc/p by neuralmag).
NM_CACHE = Path(__file__).resolve().parent / ".nm_cache"


def _build_demag(n, dx, Ms: float, p: int) -> tuple[Array, Callable, Callable]:
    """Precompute neuralmag's demag tensor `N` and the node<->cell projections.

    Returns `(N, to_cell, to_node_w)`: the (3, 3, *) rfft tensor as a single jax
    array plus the two mass-lumped projection kernels neuralmag generates for
    this mesh (pure jax functions of the field alone, mesh data bound in).
    Triggers neuralmag's one-time code generation, so call this sparingly.
    """
    mesh = nm.Mesh(tuple(n), tuple(dx))
    state = nm.State(mesh)
    # nodal m, matching the solver that produced the training data
    state.m = nm.VectorFunction(state).fill((0, 0, 1))
    state.material.Ms = Ms
    nm.DemagField(p=p, cache_dir=NM_CACHE).register(state)
    to_cell = state.resolve(nm.VectorFunction(state)._code.to_cell, ["f"])
    to_node_w = state.resolve(
        nm.VectorCellFunction(state)._code.to_node_w, ["f", "weight"]
    )
    # State stores N_demag as a stacked (3, 3, nx_pad, ny_rfft, nz) array.
    return jnp.asarray(state.N_demag), to_cell, to_node_w


class DemagField(eqx.Module):
    """Computes the demag field of a magnetization field via neuralmag.

    Call signature mirrors the model's: a single channel-first sample `m` of
    shape (3, nx+1, ny+1) (`nodal=True`, the default) or (3, nx, ny)
    (`nodal=False`, cell-centred), unit vectors, maps to the demag field of the
    same shape. Vmap externally for batches.

    The output is nondimensionalized by `Ms` (so it matches the H_ext / Ms
    convention used for the applied-field input channels); pass
    `nondim=False` for the raw A/m field.
    """

    N: Array  # (3, 3, *) demag tensor (rfft); buffer, not trained
    Ms: float = eqx.field(static=True)
    n: tuple = eqx.field(static=True)  # (nx, ny) mesh *cell* counts; nodes are n+1
    dx: tuple = eqx.field(static=True)  # cell size; the field depends on it
    p: int = eqx.field(static=True)  # neuralmag quadrature order
    nondim: bool = eqx.field(static=True)
    nodal: bool = eqx.field(static=False)  # m on the nodes (n+1) or the cells (n)
    to_cell: Callable = eqx.field(static=True)
    to_node_w: Callable = eqx.field(static=True)

    def __init__(
        self,
        n,
        dx,
        Ms: float,
        *,
        p: int = 20,
        nondim: bool = True,
        nodal: bool = False,
    ):
        self.n = tuple(int(x) for x in n)
        if len(self.n) != 2:
            raise ValueError(f"expected a 2D cell count (nx, ny), got {self.n}")
        self.Ms = float(Ms)
        self.dx = tuple(float(x) for x in dx)
        self.p = int(p)
        self.nondim = nondim
        self.nodal = nodal
        self.N, self.to_cell, self.to_node_w = _build_demag(self.n, self.dx, self.Ms, p)

    def __call__(self, m: Array) -> Array:
        # (3, h, w) -> (h, w, 3), the vector-last layout neuralmag expects.
        m = jnp.moveaxis(m, 0, -1)

        Ms_field = jnp.full(self.n, self.Ms, dtype=m.dtype)
        rho = jnp.ones(self.n, dtype=m.dtype)

        # cell-space convolution, padded to 3D and cropped back (2D mesh, nz=1)
        m_cell = self.to_cell(m) if self.nodal else m  # (nx, ny, 3)
        h = h_cell(self.N, m_cell[..., None, :], Ms_field[..., None], rho[..., None])
        h = h[:, :, 0, :]  # (nx, ny, 3) in A/m
        if self.nodal:
            h = self.to_node_w(h, Ms_field)  # (nx+1, ny+1, 3)

        if self.nondim:
            h = h / self.Ms

        return jnp.moveaxis(h, -1, 0)  # (3, h, w)


@lru_cache(maxsize=64)
def demag_cache(
    n: tuple, dx: tuple, Ms: float = 1.0, p: int = 20, *, nodal: bool = False
) -> DemagField:
    """`DemagField` for one mesh, built at most once per process.

    The tensor is what makes the model mesh-specific, so evaluating on a mesh
    other than the training one means building another one. Caching matters
    twice over: the build is O(minutes) when `.nm_cache` misses, and the
    generated projection kernels are *static* pytree fields, so a fresh
    `DemagField` per call would retrigger jit compilation on every rollout.

    Args must be hashable (tuples, not lists) — `lru_cache` keys on them.
    """
    return DemagField(n, dx, Ms=Ms, p=p, nodal=nodal)


class CoarseLLG(eqx.Module):
    """One frame of LLG micromagnetics on the data's (coarse) cell grid, computed by
    neuralmag: its own exchange, demag and Zeeman field terms and LLG right-hand
    side (`state.resolve`), integrated with diffrax Dopri5 at the tolerances
    neuralmag's `LLGSolverJAX` uses. Unlike `LLGSolver.step`, which advances
    `state.m` in place, this is a pure function of (m, h), so the emulator can vmap
    it over a batch and differentiate through it.

    neuralmag discretises m on the nodes of its mesh. The nodes are placed at the
    data's cell centres (a nodal mesh one cell smaller per axis), so the
    cell-centred data maps onto it without interpolation; the price is a magnetic
    body that ends half a cell inside the film's edge, one reason this is less
    accurate on coarse meshes than magnum.np's cell-based finite differences.

    Call: m (3, nx, ny) unit vectors, h_ext (3,) = H / Ms -> m after `dt`.
    """

    step: Callable = eqx.field(static=True)
    Ms: float = eqx.field(static=True)

    def __init__(self, n, dx, Ms, A, alpha, dt, scale_t=1e-9, rtol=1e-5, atol=1e-5):
        import diffrax as dfx
        from neuralmag.backends.jax.tensor_operations import xp_runtime
        from neuralmag.common.llg import llg_rhs

        mesh = nm.Mesh(
            (n[0] - 1, n[1] - 1), tuple(dx), (dx[0] / 2, dx[1] / 2, 0.0)
        )  # nodes at the cell centres
        state = nm.State(mesh)
        state.material.Ms = Ms
        state.material.A = A
        state.material.alpha = alpha
        state.m = nm.VectorFunction(state).fill((1.0, 0.0, 0.0))
        state.h_applied = state.tensor([0.0, 0.0, 0.0])
        nm.ExchangeField().register(state, "exchange")
        nm.DemagField(cache_dir=NM_CACHE).register(state, "demag")
        nm.ExternalField(lambda h_applied: h_applied).register(state, "external")
        nm.TotalField("exchange", "demag", "external").register(state)
        rhs = state.resolve(
            lambda h, m, material__alpha: llg_rhs(xp_runtime, h, m, material__alpha),
            ["m", "h_applied"],
        )
        term = dfx.ODETerm(lambda t, m, h: scale_t * rhs(m, h))
        controller = dfx.PIDController(rtol=rtol, atol=atol)

        def step(m, h):  # m (nx, ny, 3) on the nodes, h (3,) in A/m
            sol = dfx.diffeqsolve(
                term,
                dfx.Dopri5(),
                t0=0.0,
                t1=dt / scale_t,
                dt0=1e-14 / scale_t,
                y0=m,
                args=h,
                stepsize_controller=controller,
                saveat=dfx.SaveAt(t1=True),
                max_steps=4096,
            )
            m = sol.ys[-1]
            return m / jnp.linalg.norm(m, axis=-1, keepdims=True)

        self.step = step
        self.Ms = float(Ms)

    def __call__(self, m, h_ext):
        m = self.step(jnp.moveaxis(m, 0, -1), h_ext * self.Ms)
        return jnp.moveaxis(m, -1, 0)


@lru_cache(maxsize=64)
def llg_cache(n: tuple, dx: tuple, alpha: float | None = None) -> CoarseLLG:
    """`CoarseLLG` for one mesh of the dataset's permalloy, one frame (10 ps) per
    call, built at most once per process like `demag_cache`; `alpha` overrides the
    damping (1.0 for a relaxation)."""
    from datagen.generate_varied_field import DT, MATERIAL

    a = MATERIAL["alpha"] if alpha is None else alpha
    return CoarseLLG(n, dx, MATERIAL["Ms"], MATERIAL["A"], a, DT)
