"""Differentiable LLG physics loss: computes `m_{t+1}` on the fly instead of loading it.

The training loop (`training.loss_fn`) supervises the model against a precomputed
`m_{t+1}` read off disk by `LLGStepperSource`. This module computes that target
directly by integrating the LLG equation, so the model can be supervised on *any*
`m_t` -- not only the frames a solver happened to write out.

The physics is entirely neuralmag's: `state.resolve(llg_rhs, ["m", "h_external"])`
returns the full `dm/dt` (exchange + demag + external, with the mesh and Ms/A/alpha
baked in) as a pure function that jits, vmaps and differentiates. That is exactly how
neuralmag's own `LLGSolverJAX` builds its ODE term, so nothing here extends the library.
We integrate it with fixed-step RK4 rather than neuralmag's adaptive diffrax solver:
an adaptive solver's step count is data-dependent, which cannot be vmapped over a batch.

Conventions match the rest of the package: `m` is channel-first `(3, nx, ny)` per sample,
and `H_ext` is nondimensionalised by `Ms` (the `"H"` key `data.py` yields, and what the
model consumes). SI lives entirely inside this file -- `Ms` is the only unit conversion.

    physics = LLGPhysicsLoss(n=(256, 256, 1), dx=(5e-9, 5e-9, 3e-9), Ms=8e5, A=1.3e-11)
    loss = physics(m0, model, H, dt=1e-11)   # m0 (B,3,256,256), H (B,3)

NOTE (measured, 2026-07-16): the training data was generated by **magnum.np**, whose
exchange is a 6-point FD Laplacian; neuralmag's `ExchangeField` is an FEM form. On real
data they disagree by max 3.5e-2 against a per-step signal of 4.2e-2 -- and that gap does
*not* shrink with more substeps, because it is a discretisation difference, not
integration error. This loss therefore enforces neuralmag's discretisation of the LLG,
which is not bit-identical to the trajectories in `m.npy`. That is a deliberate choice;
swapping `_build_rhs`'s `nm.ExchangeField()` for an FD stencil reproduces the data to
2.5e-5 if matching the dataset ever matters more than staying inside neuralmag.
"""

import math
from typing import Callable

import equinox as eqx
import jax
import jax.numpy as jnp
from jaxtyping import Array, PyTree
from scipy import constants

import neuralmag as nm
from neuralmag.backends.jax.llg_solver_jax import llg_rhs
from neuralmag.common.llg import GAMMA_PRIME

from llg_emulator.data import BASE_STEP_TIME

# RK4 is stable for |lambda*dt| <~ 2.8 on the imaginary axis; integrate the stiffest
# exchange mode at 2.0 to leave margin. Measured: at dt=1e-11 the stiff mode is 18.3 rad,
# so a substep count that ignores dt blows up on the stride-2 (dt=2e-11) pairs.
_RK4_STABLE_ANGLE = 2.0


def _build_rhs(n, dx, Ms: float, A: float, alpha: float, p: int) -> Callable:
    """Resolve neuralmag's LLG rhs into a pure `(m, h_external) -> dm/dt`.

    Cell-space on a 3D `(nx, ny, 1)` mesh: that is the layout the data and the model
    use. (neuralmag's docs prefer a 2D nodal mesh for thin films, but that gives
    `(nx+1, ny+1, 3)` -- the wrong grid for this repo.) Material params and the mesh are
    baked in at resolve time and cannot be changed afterwards.
    """
    mesh = nm.Mesh(tuple(n), tuple(dx))
    state = nm.State(mesh)
    state.material.Ms = Ms
    state.material.A = A
    state.material.alpha = alpha
    state.m = nm.VectorCellFunction(state).fill((1.0, 0.0, 0.0))
    nm.ExchangeField().register(state, "exchange")
    nm.DemagField(p=p).register(state, "demag")
    # Registered only so `h_external` resolves to a runtime argument; the tensor it is
    # built with is never used. A (3,) H broadcasts over the cell grid at call time.
    nm.ExternalField(nm.VectorCellFunction(state).fill((0.0, 0.0, 0.0))).register(
        state, "external"
    )
    nm.TotalField("exchange", "demag", "external").register(state)
    return state.resolve(llg_rhs, ["m", "h_external"])


class LLGPhysicsLoss(eqx.Module):
    """MSE of the model's `m_{t+1}` against one integrated from the LLG equation.

    `step` is the pure physics (`m_t -> m_{t+1}`, one sample, vmap-able); `__call__` is
    the loss over a batch. The resolved rhs is a static leaf -- it holds no trainable
    arrays, so unlike `model.demag.N` it needs no `trainable_filter` handling.
    """

    rhs: Callable = eqx.field(static=True)  # resolved neuralmag dm/dt; not a pytree leaf
    n: tuple = eqx.field(static=True)  # (nx, ny, nz) mesh cell counts
    Ms: float = eqx.field(static=True)
    substeps: int | None = eqx.field(static=True)
    stiff_rate: float = eqx.field(static=True)  # rad/s of the stiffest exchange mode

    def __init__(
        self,
        n,
        dx,
        Ms: float,
        A: float,
        *,
        alpha: float = 0.02,  # not derivable: the LLG damping term needs it
        p: int = 20,
        substeps: int | None = None,  # None -> derived from dt for RK4 stability
    ):
        self.n = tuple(int(x) for x in n)
        self.Ms = float(Ms)
        self.substeps = substeps
        self.rhs = _build_rhs(self.n, dx, self.Ms, float(A), float(alpha), p)

        # Stiffest mode: gamma' * (2A / mu0 Ms) * max eigenvalue of the FD laplacian.
        # Axes with one cell have no neighbours and so do not contribute.
        gamma_prime = GAMMA_PRIME / (1.0 + alpha**2)
        lap_max = sum(4.0 / d**2 for d, c in zip(dx, self.n) if c > 1)
        self.stiff_rate = gamma_prime * (2.0 * A / (constants.mu_0 * self.Ms)) * lap_max

    def _nsub(self, dt: float) -> int:
        if self.substeps is not None:
            return self.substeps
        return max(1, math.ceil(dt * self.stiff_rate / _RK4_STABLE_ANGLE))

    def step(self, m: Array, H_ext: Array, dt: float) -> Array:
        """Integrate `m` (3, nx, ny) forward by `dt`. `H_ext` is (3,), in units of Ms."""
        nx, ny, nz = self.n
        m_cell = jnp.moveaxis(m, 0, -1).reshape(nx, ny, nz, 3)
        h_ext = H_ext * self.Ms  # -> A/m, the SI units neuralmag's rhs expects

        h = dt / self._nsub(dt)

        def rk4(mc, _):
            k1 = self.rhs(mc, h_ext)
            k2 = self.rhs(mc + 0.5 * h * k1, h_ext)
            k3 = self.rhs(mc + 0.5 * h * k2, h_ext)
            k4 = self.rhs(mc + h * k3, h_ext)
            return mc + (h / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4), None

        m_cell, _ = jax.lax.scan(rk4, m_cell, None, length=self._nsub(dt))
        # LLG conserves |m| analytically but RK4 does not; the generator and the model
        # both emit unit-norm m, so put the target back on the same manifold.
        m_cell = m_cell / jnp.linalg.norm(m_cell, axis=-1, keepdims=True)
        return jnp.moveaxis(m_cell[:, :, 0, :], -1, 0)

    def __call__(self, m_t: Array, model: PyTree, H_ext: Array, dt: float) -> Array:
        """Physics loss over a batch: `m_t` (B, 3, nx, ny), `H_ext` (B, 3) in units of Ms.

        `model` is invoked exactly as `training.loss_fn` does, including the (4,)
        conditioning vector; `dt` supplies the stride channel the dataloader encodes as
        `s0 = log2(stride)`.
        """
        s0 = jnp.log2(jnp.asarray(dt) / BASE_STEP_TIME)
        cond = jnp.concat((H_ext, jnp.broadcast_to(s0, (*H_ext.shape[:-1], 1))), axis=-1)
        # model is closed over, never an argument to vmap -- vmapping over a pytree of
        # weights would try to map their leading axis.
        m1_pred = jax.vmap(model)(m_t, cond)
        m1_phys = jax.vmap(lambda m, H: self.step(m, H, dt))(m_t, H_ext)
        return jnp.mean(jnp.square(m1_pred - m1_phys))


if __name__ == "__main__":
    import jax.random as jr

    from llg_emulator.model import LLGEmulator, ModelConfig
    from llg_emulator.physics import DemagField

    n, dx, Ms, A = (16, 16, 1), (5e-9, 5e-9, 3e-9), 8e5, 1.3e-11
    physics = LLGPhysicsLoss(n=n, dx=dx, Ms=Ms, A=A)

    key = jr.PRNGKey(0)
    m = jr.normal(key, (2, 3, *n[:2]))
    m = m / jnp.linalg.norm(m, axis=1, keepdims=True)
    H = jnp.tile(jnp.array([-19576.0, 3421.8, 0.0]) / Ms, (2, 1))
    dt = 1e-11

    # substeps must clear the RK4 stability angle for the stiffest exchange mode
    assert dt * physics.stiff_rate / physics._nsub(dt) <= _RK4_STABLE_ANGLE
    print(f"stiff mode {dt * physics.stiff_rate:.1f} rad -> {physics._nsub(dt)} substeps"
          f"; dt=2e-11 -> {physics._nsub(2e-11)}")

    m1 = physics.step(m[0], H[0], dt)
    assert m1.shape == (3, *n[:2]), m1.shape
    assert jnp.allclose(jnp.linalg.norm(m1, axis=0), 1.0, atol=1e-5), "not unit-norm"

    # dt -> 0 is the identity map
    assert jnp.abs(physics.step(m[0], H[0], 1e-18) - m[0]).max() < 1e-6

    # the integration is converged: 4x the substeps must not move the answer much
    fine = LLGPhysicsLoss(n=n, dx=dx, Ms=Ms, A=A, substeps=4 * physics._nsub(dt))
    err = jnp.abs(m1 - fine.step(m[0], H[0], dt)).max()
    assert err < 1e-3, f"RK4 not converged: {err:.2e}"
    print(f"RK4 self-convergence vs 4x substeps: {err:.2e}")

    model = LLGEmulator(
        ModelConfig(hidden_channels=4, num_blocks=1, mesh_n=n, mesh_dx=dx),
        DemagField(n=n, dx=dx, Ms=1.0),
        key=key,
    )
    loss, grad = eqx.filter_value_and_grad(
        lambda mdl: physics(m, mdl, H, dt)
    )(model)
    leaves = [g for g in jax.tree_util.tree_leaves(eqx.filter(grad, eqx.is_inexact_array))]
    assert loss > 0 and jnp.isfinite(loss), loss
    assert leaves and all(jnp.isfinite(g).all() for g in leaves), "non-finite grads"
    assert any(jnp.abs(g).max() > 0 for g in leaves), "no gradient reached the model"
    print(f"loss {loss:.4f}  grad leaves {len(leaves)}  "
          f"max|g| {max(float(jnp.abs(g).max()) for g in leaves):.3e}")
    print("ok")
