"""Demag (magnetostatic) field calculator built on neuralmag.

The demag field is the long-range, geometry-coupled term in the LLG effective
field: solving it cheaply and exactly here lets the neural surrogate spend its
capacity on the short-range interactions (exchange, anisotropy) instead of
re-learning a global convolution.

neuralmag computes the field as an FFT convolution of the magnetization with a
precomputed demag tensor `N` that depends only on the mesh geometry (cell count
+ cell size). We build that tensor once via neuralmag's `State`/`DemagField`
machinery at construction time, store it as a (non-trainable) buffer, and apply
neuralmag's `h_cell` convolution on every call. The module is therefore a pure,
jit/vmap-friendly Equinox module with no learnable parameters.

**Discretization.** The solver (`src/datagen/generate.py`) runs on a *2D* mesh of
`n = (nx, ny)` cells and stores `m` on the **nodes**, i.e. `(nx+1, ny+1)` values —
that is what the training data contains. The convolution, however, is cell-based,
so a nodal call has to follow neuralmag's own node kernel (see
`neuralmag.field_terms.demag_field.DemagField.register`):

    m_node --to_cell--> m_cell --h_cell--> h_cell --to_node_w--> h_node

Both projections are mass-lumped and generated by neuralmag for this mesh; we
resolve them once at construction. Skipping them (treating the nodal grid as a
cell grid) is not a harmless approximation: it gets the field wrong by >100%.
"""

import logging as _logging
from collections.abc import Callable
from functools import lru_cache
from pathlib import Path

import equinox as eqx
import jax.numpy as jnp
import neuralmag as nm
from jaxtyping import Array
from neuralmag.backends.jax.demag_field import h_cell

# neuralmag logs its setup at INFO on every State build (one per model
# construction); keep the training/eval output readable.
nm.set_log_level(_logging.WARNING)

# The mesh geometry is fixed across runs, so the demag tensor is built once and
# reused (keyed on n/dx/pbc/p by neuralmag). Shared with src/datagen.
NM_CACHE = Path(__file__).resolve().parents[2] / ".nm_cache"


def _build_demag(n, dx, Ms: float, p: int) -> tuple[Array, Callable, Callable]:
    """Precompute neuralmag's demag tensor `N` and the node<->cell projections.

    Returns `(N, to_cell, to_node_w)`: the (3, 3, *) rfft tensor as a single jax
    array plus the two mass-lumped projection kernels neuralmag generates for
    this mesh (pure jax functions of the field alone, mesh data bound in).
    Triggers neuralmag's one-time code generation, so call this sparingly.
    """
    mesh = nm.Mesh(tuple(n), tuple(dx))
    state = nm.State(mesh)
    # nodal m, matching the solver that produced the training data
    state.m = nm.VectorFunction(state).fill((0, 0, 1))
    state.material.Ms = Ms
    nm.DemagField(p=p, cache_dir=NM_CACHE).register(state)
    to_cell = state.resolve(nm.VectorFunction(state)._code.to_cell, ["f"])
    to_node_w = state.resolve(nm.VectorCellFunction(state)._code.to_node_w, ["f", "weight"])
    # State stores N_demag as a stacked (3, 3, nx_pad, ny_rfft, nz) array.
    return jnp.asarray(state.N_demag), to_cell, to_node_w


class DemagField(eqx.Module):
    """Computes the demag field of a magnetization field via neuralmag.

    Call signature mirrors the model's: a single channel-first *nodal* sample
    `m` of shape (3, nx+1, ny+1) (unit vectors) maps to the demag field of the
    same shape. Vmap externally for batches.

    The output is nondimensionalized by `Ms` (so it matches the H_ext / Ms
    convention used for the applied-field input channels); pass
    `nondim=False` for the raw A/m field.
    """

    N: Array  # (3, 3, *) demag tensor (rfft); buffer, not trained
    Ms: float = eqx.field(static=True)
    n: tuple = eqx.field(static=True)  # (nx, ny) mesh *cell* counts; nodes are n+1
    dx: tuple = eqx.field(static=True)  # cell size; the field depends on it
    p: int = eqx.field(static=True)  # neuralmag quadrature order
    nondim: bool = eqx.field(static=True)
    to_cell: Callable = eqx.field(static=True)
    to_node_w: Callable = eqx.field(static=True)

    def __init__(
        self,
        n,
        dx,
        Ms: float,
        *,
        p: int = 20,
        nondim: bool = True,
    ):
        self.n = tuple(int(x) for x in n)
        if len(self.n) != 2:
            raise ValueError(f"expected a 2D cell count (nx, ny), got {self.n}")
        self.Ms = float(Ms)
        self.dx = tuple(float(x) for x in dx)
        self.p = int(p)
        self.nondim = nondim
        self.N, self.to_cell, self.to_node_w = _build_demag(self.n, self.dx, self.Ms, p)

    def __call__(self, m: Array) -> Array:
        # (3, nx+1, ny+1) -> (nx+1, ny+1, 3) node-vector layout neuralmag expects.
        m_node = jnp.moveaxis(m, 0, -1)

        Ms_field = jnp.full(self.n, self.Ms, dtype=m.dtype)
        rho = jnp.ones(self.n, dtype=m.dtype)

        # cell-space convolution, padded to 3D and cropped back (2D mesh, nz=1)
        m_cell = self.to_cell(m_node)  # (nx, ny, 3)
        h = h_cell(self.N, m_cell[..., None, :], Ms_field[..., None], rho[..., None])
        h = self.to_node_w(h[:, :, 0, :], Ms_field)  # (nx+1, ny+1, 3) in A/m

        if self.nondim:
            h = h / self.Ms

        return jnp.moveaxis(h, -1, 0)  # (3, nx+1, ny+1)


@lru_cache(maxsize=8)
def demag_for(n: tuple, dx: tuple, Ms: float = 1.0, p: int = 20) -> DemagField:
    """`DemagField` for one mesh, built at most once per process.

    The tensor is what makes the model mesh-specific, so evaluating on a mesh
    other than the training one means building another one. Caching matters
    twice over: the build is O(minutes) when `.nm_cache` misses, and the
    generated projection kernels are *static* pytree fields, so a fresh
    `DemagField` per call would retrigger jit compilation on every rollout.

    Args must be hashable (tuples, not lists) — `lru_cache` keys on them.
    """
    return DemagField(n, dx, Ms=Ms, p=p)
