seed = 0
epochs = 8
checkpoint_every = 4

[model]
hidden_channels = 32
num_blocks = 2
activation = "gelu"

[data]
size = "med"
batch_size = 192
viz_sample = "sp4/sample_0"

[optim]
name = "adam"
lr = 1e-4

[wandb]
project = "llg-emulator-test"
mode = "online"